---

stages:
    - build
    - security

variables:
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
    
include:
    - remote: 'https://gitlab.com/verademo/security-ci-includes/-/raw/master/sast-scan.yml'
    - remote: 'https://gitlab.com/verademo/security-ci-includes/-/raw/master/sca-scan.yml'
   
image: maven:3.6-jdk-11

cache:
    key: "$CI_JOB_NAME"
    paths:
        - .m2/repository

package:
    stage: build
    script:
        - 'mvn $MAVEN_CLI_OPTS package'
    artifacts:
        paths:
            - target

sca-scan:
    stage: security
    extends: .sca-scan
    
sast-pipeline-scan:
    stage: security
    extends: .sast-pipeline-scan
    except:
        - master
    variables:
        VERACODE_FILEPATH: 'target/demo-*.war'

